language: python

python:
  - "3.6"

env:
  global:
    - CC_TEST_REPORTER_ID=e2b6e7efc75fe998f655196d4fbc6d836286c32597274a40eb927a4cd1728918

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov

script:
  - export FLASK_ENV=development
  - pytest --cov=app/tests/v1

after_success:
  - coveralls
  - codecov --84aa3009-9723-47c4-b8f1-2e11cc7a6563

cache: pip
